# pctl/test

all : 
	make -C dp_array
	make -C dp_deque
	make -C dp_forward_list
	make -C dp_list
	make -C dp_map
	make -C dp_set
	make -C dp_unordered_map
	make -C dp_unordered_set
	make -C dp_vector

clean :
	make -C dp_array clean
	make -C dp_deque clean
	make -C dp_forward_list clean
	make -C dp_list clean
	make -C dp_map clean
	make -C dp_set clean
	make -C dp_unordered_map clean
	make -C dp_unordered_set clean
	make -C dp_vector clean

test :
	make -C dp_array test
	make -C dp_deque test
	make -C dp_forward_list test
	make -C dp_list test
	make -C dp_map test
	make -C dp_set test
	make -C dp_unordered_map test
	make -C dp_unordered_set test
	make -C dp_vector test
